services:
    _defaults:
        # Calculate the required dependencies from type declarations of the constructor and inject methods.
        autowire: true
        # Automatically add symfony service tags based on implemented interfaces or base classes.
        autoconfigure: true
        public: false

    Lex\Notifications\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'

    Lex\Notifications\NotificationDispatcherInterface:
        class: Lex\Notifications\NotificationManager
        public: true

    # All classes that implement ChannelInterface will have that tag and therefore be registered as a channel and injected into the NotificationManager.
    _instanceof:
        Lex\Notifications\Channel\ChannelInterface:
            tags:
                - name: 'notifications.channel'

    Lex\Notifications\Queue\Handler\SendQueuedNotificationNow:
        tags:
            - name: 'messenger.message_handler'